# This is a simple ansible playbook for installing packages needed by the
# udisks test suite.
# You can do this by using 'make install-requires' or manually using
# 'ansible-playbook -K -i "localhost," -c local install-test-dependencies.yml'
# Currently only Fedora and CentOS are supported by this playbook.

---
- hosts: all
  become: true

  tasks:
  - name: Include tasks from udisks-tasks.yml
    ansible.builtin.include_tasks: udisks-tasks.yml
